### ISSUE TITLE
BST construction in Python and CPP

### ISSUE THREAD

**Issue by suyash2796** [suyash2796/CSCognisanse#26]
Write program to construct BST

**Comment by davidqdo** [comment]
Hello, I was wondering if I can help you with this issue. I can work on it right now and when I'm done I'll send you a pull request to see if the code is alright with you. Hopefully I could be of some help for this

**Comment by suyash2796** [comment]
Sure @davidqdo ! It would be great. Please write your code in this directory CSCognisanse/BST/.
Thanks!

**Comment by suyash2796** [comment]
code changes completed by contributor @davidqdo. Closing this issue.
