### ISSUE TITLE
Implement Max sum subarray problem in Go

### ISSUE THREAD

**Issue by suyash2796** [suyash2796/CSCognisanse#32]
python solution for reference:
https://github.com/suyash2796/CSCognisanse/blob/master/dp/kadanes/python/max_sum_subarray.py

**Comment by CHuante** [comment]
hi, id like to contribute to this! just tell me what language and where to put it and ill have it done!

**Comment by suyash2796** [comment]
hi @CHuante - Thank you for showing interest!
It would be great if you can solve this problem in Golang.

Please put your program here:
https://github.com/suyash2796/CSCognisanse/blob/master/dp/kadanes/GO/max_sum_subarray.go

Please refer readme.md for problem statement:
https://github.com/suyash2796/CSCognisanse/blob/master/dp/kadanes/readme.md

solutions in python/cpp are also there if you want to refer.

Thank you!

**Comment by CHuante** [comment]
Finished the program and sent a pull request, is everything in order?

**Comment by suyash2796** [comment]
> Finished the program and sent a pull request, is everything in order?

i have requested a change. Could you please
